export const dataCeline = {
	generic: [
		{
			ask: "Lauren Fraser",
			text: "Vous ne voulez pas vous concentrer sur l'enquête plutôt que d'ennuyer les membres de l'équipe ?",
			srcComment: "sounds/403-repliques-celine-8.wav",
		},
		{
			ask: "Céline Valluy",
			text: "Vous n'avez pas une enquête à résoudre plutôt que de vous inquiéter de ma vie ?",
			srcComment: "sounds/403-repliques-celine-8.wav",
		},
		{
			ask: "Tim Lonewood",
			text: "Vous ne voulez pas vous concentrer sur l'enquête plutôt que d'ennuyer les membres de l'équipe ?",
			srcComment: "sounds/403-repliques-celine-8.wav",
		},
		{
			ask: "Raphaëlle Sanchez",
			text: "Vous ne voulez pas vous concentrer sur l'enquête plutôt que d'ennuyer les membres de l'équipe ?",
			srcComment: "sounds/403-repliques-celine-8.wav",
		},
		{
			ask: "Adèle Leinu",
			text: "Vous ne voulez pas vous concentrer sur l'enquête plutôt que d'ennuyer les membres de l'équipe ?",
			srcComment: "sounds/403-repliques-celine-8.wav",
		},
		{
			ask: "Jacqueline Garraud",
			text: "Je ne la trouve pas, est-ce qu'elle n'est pas connue sous un autre nom ?",
		},
		{
			ask: "Stella Louiseberg",
			text:
				"Je n'ai rien trouvé concernant cette personne dans les archives de la police. Vous avez pensé à demander à Tim ?",
		},
	],
	box1: [
		{
			ask: "Alphonse St-Yves",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive1",
			title: "Archives Alphonse StYves",
			src: "assets/archive/1_Archives_Alphonse_StYves.jpg",
			status: false,
		},
		{
			ask: "Armand Beaux",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive2",
			title: "Archives Armand Beaux",
			src: "assets/archive/1_Archives_Armand_Beaux.jpg",
			status: false,
		},
		{
			ask: "Axelle Charpentier",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive3",
			title: "Archives Axelle Charpentier",
			src: "assets/archive/1_Archives_Axelle_Charpentier.jpg",
			status: false,
		},
		{
			ask: "Camille Michaux",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive4",
			title: "Archives Camille Michaux",
			src: "assets/archive/1_Archives_Camille_Michaux.jpg",
			status: false,
		},
		{
			ask: "Charles Garraud",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive5",
			title: "Archives Charles Garraud",
			src: "assets/archive/1_Archives_Charles_Garraud.jpg",
			status: false,
		},
		{
			ask: "Christian Patenaud",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive6",
			title: "Archives Christian Patenaud",
			src: "assets/archive/1_Archives_Christian_Patenaude.jpg",
			status: false,
		},
		{
			ask: "Christophe Brunelle",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive7",
			title: "Archives Christophe Brunelle",
			src: "assets/archive/1_Archives_Christophe_Brunelle.jpg",
			status: false,
		},
		{
			ask: "Didier Rodin",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive8",
			title: "Archives Didier Rodin",
			src: "assets/archive/1_Archives_Didier_Rodin.jpg",
			status: false,
		},
		{
			ask: "Elisabeth Montency",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive9",
			title: "Archives Elisabeth Monrency",
			src: "assets/archive/1_Archives_Elisabeth_Monrency.jpg",
			status: false,
		},
		{
			ask: "Elodie Bouchard",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive10",
			title: "Archives Elodie Bouchard",
			src: "assets/archive/1_Archives_Elodie_Bouchard.jpg",
			status: false,
		},
		{
			ask: "Emmanuel Deslauriers",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive11",
			title: "Archives Emmanuel Deslauriers",
			src: "assets/archive/1_Archives_Emmanuel_Deslauriers.jpg",
			status: false,
		},
		{
			ask: "Eugenie Courbis",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive12",
			title: "Archives Eugenie Courbis",
			src: "assets/archive/1_Archives_Eugenie_Courbis.jpg",
			status: false,
		},
		{
			ask: "Frederic Masse",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive13",
			title: "Archives Frederic Masse",
			src: "assets/archive/1_Archives_Frederic_Masse.jpg",
			status: false,
		},
		{
			ask: "Jacqueline Houdin",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive14",
			title: "Archives Jacqueline Houdin",
			src: "assets/archive/1_Archives_Jacqueline_Houdin.jpg",
			status: false,
		},
		{
			ask: "Johanna Lesbourg",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive15",
			title: "Archives Johanna Lesbourg",
			src: "assets/archive/1_Archives_Johanna_Lesbourg.jpg",
			status: false,
		},
		{
			ask: "Marianne Chauve",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive16",
			title: "Archives Marianne Chauve",
			src: "assets/archive/1_Archives_Marianne_Chauve.jpg",
			status: false,
		},
		{
			ask: "Marie Marquis",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive17",
			title: "Archives Marie Marquis",
			src: "assets/archive/1_Archives_Marie_Marquis.jpg",
			status: false,
		},
		{
			ask: "Maxence Maret",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive18",
			title: "Archives Maxence Maret",
			src: "assets/archive/1_Archives_Maxence_Maret.jpg",
			status: false,
		},
		{
			ask: "Nicolas Chaussée",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive19",
			title: "Archives Nicolas Chaussee",
			src: "assets/archive/1_Archives_Nicolas_Chaussee.jpg",
			status: false,
		},
		{
			ask: "Patrick O'Neil",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive20",
			title: "Archives Patrick O'Neil",
			src: "assets/archive/1_Archives_Patrick_Oneill.jpg",
			status: false,
		},
		{
			ask: "Robert Dumont",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive21",
			title: "Archives Robert Dumont",
			src: "assets/archive/1_Archives_Robert_Dumont.jpg",
			status: false,
		},
		{
			ask: "Violaine Celier",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive22",
			title: "Archives Violaine Celier",
			src: "assets/archive/1_Archives_Violaine_Celier.jpg",
			status: false,
		},
		{
			ask: "Xavier Monrency",
			text:
				"Voilà ce que j'ai trouvé. Je vous ai aussi mis son rapport Legiste dans l'onglet Historique, n'hésitez pas à le consulter :",
			id: "box1archive23",
			title: "Archives Xavier Monrency",
			src: "assets/archive/1_Archives_Xavier_Monrency.jpg",
			status: false,
		},
		{
			ask: "Yannick Becot",
			text: "Voilà ce que j'ai trouvé :",
			id: "box1archive24",
			title: "Archives Yannick Becot",
			src: "assets/archive/1_Archives_Yannick_Becot.jpg",
			status: false,
		},
	],
	box2: [
		{
			ask: "Aaron King",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive1",
			title: "Archives Aaron King",
			src: "assets/archive/2_Archives_Aaron_King.jpg",
			status: false,
		},
		{
			ask: "Ainmir Oconradh",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive2",
			title: "Archives Ainmir Oconradh",
			src: "assets/archive/2_Archives_Ainmire_Oconradh.jpg",
			status: false,
		},
		{
			ask: "Annelijn Dikboom",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive3",
			title: "Archives Annelijn Dikboom",
			src: "assets/archive/2_Archives_Annelijn_dikboom.jpg",
			status: false,
		},
		{
			ask: "Annina Kurschner",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive4",
			title: "Archives Annina Kurschner",
			src: "assets/archive/2_Archives_Annina_Kurschner.jpg",
			status: false,
		},
		{
			ask: "Augustas Alsys",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive5",
			title: "Archives Augustas Alsys",
			src: "assets/archive/2_Archives_Augustas_Alsys.jpg",
			status: false,
		},
		{
			ask: "Bogdana Nikol",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive6",
			title: "Archives Bogdana Nikol",
			src: "assets/archive/2_Archives_Bogdana_Nikol.jpg",
			status: false,
		},
		{
			ask: "Daisy Vandenbulcke",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive7",
			title: "Archives Daisy Vandenbulcke",
			src: "assets/archive/2_Archives_Daisy_Vandenbulcke.jpg",
			status: false,
		},
		{
			ask: "Dimosthenis Rigas",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive8",
			title: "Archives Dimosthenis Rigas",
			src: "assets/archive/2_Archives_Dimosthenis_Rigas.jpg",
			status: false,
		},
		{
			ask: "Dominik Jele",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive9",
			title: "Archives Dominik Jele",
			src: "assets/archive/2_Archives_Dominik_Jele.jpg",
			status: false,
		},
		{
			ask: "Edvard Kallio",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive10",
			title: "Archives Edvard Kallio",
			src: "assets/archive/2_Archives_Edvard_Kallio.jpg",
			status: false,
		},
		{
			ask: "Elias Varelas",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive11",
			title: "Archives Elias Varelas",
			src: "assets/archive/2_Archives_Elias_Varelas.jpg",
			status: false,
		},
		{
			ask: "Elimena Furino",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive12",
			title: "Archives Elimena Furino",
			src: "assets/archive/2_Archives_Elimena_Furino.jpg",
			status: false,
		},
		{
			ask: "Eliza Gaewska",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive13",
			title: "Archives Eliza Gaewska",
			src: "assets/archive/2_Archives_Eliza_Gaewska.jpg",
			status: false,
		},
		{
			ask: "Ere Jakobson",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive14",
			title: "Archives Ere Jakobson",
			category: "Archive",
			status: false,
		},
		{
			ask: "Francois Duchamp",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive15",
			title: "Archives Francois Duchamp",
			src: "assets/archive/2_Archives_Francois_Duchamp.jpg",
			status: false,
		},
		{
			ask: "Horasiu Prunea",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive16",
			title: "Archives Horasiu Prunea",
			src: "assets/archive/2_Archives_Horasiu_Prunea.jpg",
			status: false,
		},
		{
			ask: "Imelda Tuzzolino",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive17",
			title: "Archives Imelda Tuzzolino",
			src: "assets/archive/2_Archives_Imelda_Tuzzolino.jpg",
			status: false,
		},
		{
			ask: "Ivar Mortensen",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive18",
			title: "Archives Ivar Mortensen",
			src: "assets/archive/2_Archives_Ivar_Mortensen.jpg",
			status: false,
		},
		{
			ask: "James Chambers",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive19",
			title: "Archives James Chambers",
			src: "assets/archive/2_Archives_James_Chambers.jpg",
			status: false,
		},
		{
			ask: "Janina Muster",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive20",
			title: "Archives Janina Muster",
			src: "assets/archive/2_Archives_Janina_Muster.jpg",
			status: false,
		},
		{
			ask: "Jorn Frenzel",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive21",
			title: "Archives Jorn Frenzel",
			src: "assets/archive/2_Archives_Jorn_Frenzel.jpg",
			status: false,
		},
		{
			ask: "Karina Galicka",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive22",
			title: "Archives Karina Galicka",
			src: "assets/archive/2_Archives_Karina_Galicka.jpg",
			status: false,
		},
		{
			ask: "Konstantin Wallner",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive23",
			title: "Archives Konstantin Wallner",
			src: "assets/archive/2_Archives_Konstantin_Wallner.jpg",
			status: false,
		},
		{
			ask: "Laura Tavernier",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive24",
			title: "Archives Laura Tavernier",
			src: "assets/archive/2_Archives_Laura_Tavernier.jpg",
			status: false,
		},
		{
			ask: "Lina Syren",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive25",
			title: "Archives Lina Syren",
			src: "assets/archive/2_Archives_Lina_Syren.jpg",
			status: false,
		},
		{
			ask: "Linda Reynolds",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive26",
			title: "Archives Linda Reynolds",
			src: "assets/archive/2_Archives_Linda_Reynolds.jpg",
			status: false,
		},
		{
			ask: "Marian Bilek",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive27",
			title: "Archives Marian Bilek",
			src: "assets/archive/2_Archives_Marian_Bilek.jpg",
			status: false,
		},
		{
			ask: "Marike Vonbraun",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive28",
			title: "Archives Marike Vonbraun",
			src: "assets/archive/2_Archives_Marike_Vonbraun.jpg",
			status: false,
		},
		{
			ask: "Martin Richard",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive29",
			title: "Archives Martin Richard",
			src: "assets/archive/2_Archives_Martin_Richard.jpg",
			status: false,
		},
		{
			ask: "Mason Reynolds",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive30",
			title: "Archives Mason Reynolds",
			src: "assets/archive/2_Archives_Mason_Reynolds.jpg",
			status: false,
		},
		{
			ask: "Petar Cojocaru",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive31",
			title: "Archives Petar Cojocaru",
			src: "assets/archive/2_Archives_Petar_Cojocaru.jpg",
			status: false,
		},
		{
			ask: "Riano Della Valle",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive32",
			title: "Archives Riano Della Valle",
			src: "assets/archive/2_Archives_Riano_Della_Valle.jpg",
			status: false,
		},
		{
			ask: "Samuel Perry",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive33",
			title: "Archives Samuel Perry",
			src: "assets/archive/2_Archives_Samuel_Perry.jpg",
			status: false,
		},
		{
			ask: "Taneli Tuominen",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive34",
			title: "Archives Taneli Tuominen",
			src: "assets/archive/2_Archives_Taneli_Tuominen.jpg",
			status: false,
		},
		{
			ask: "Timo Sladie",
			text: "Voilà ce que j'ai trouvé :",
			id: "box2archive35",
			title: "Archives Timo Sladie",
			src: "assets/archive/2_Archives_Timo_Sladie.jpg",
			status: false,
		},
	],
	box3: [
		{
			ask: "Estelle Barloigus",
			text: "Je ne trouve rien sur cette personne",
			status: false,
		},
		{
			ask: "Loic Valluy",
			text: "Je ne trouve rien sur cette personne",
			status: false,
		},
		{
			ask: "Agnes Vouchiar",
			text: "Voilà ce que j'ai trouvé :",
			id: "box3archive1",
			title: "Archives Agnes Vouchiar",
			src: "assets/archive/3_Archives_Agnes_Vouchiar.jpg",
			status: false,
		},
		{
			ask: "Giuseppe Rossi",
			text: "Voilà ce que j'ai trouvé :",
			id: "box3archive2",
			title: "Archives Giuseppe Rossi",
			src: "assets/archive/3_Archives_Giuseppe_Rossi.jpg",
			status: false,
		},
		{
			ask: "Leonie Brugmann",
			text: "Voilà ce que j'ai trouvé :",
			id: "box3archive3",
			title: "Archives Leonie Brugmann",
			src: "assets/archive/3_Archives_Leonie_Brugmann.jpg",
			status: false,
		},
		{
			ask: "Maria Gruber",
			text: "Voilà ce que j'ai trouvé :",
			id: "box3archive4",
			title: "Archives Maria Gruber",
			src: "assets/archive/3_Archives_Maria_Gruber.jpg",
			status: false,
		},
		{
			ask: "Yann Lacroix",
			text: "Voilà ce que j'ai trouvé :",
			id: "box3archive5",
			title: "Archives Yann Lacroix",
			src: "assets/archive/3_Archives_Yann_Lacroix.jpg",
			status: false,
		},
	],
};
