export const dataHistory = {
	// ----- BOX 1 ----- //

	box1: [
		// ----- ARCHIVES ----- //

		{
			id: "box1archive1",
			title: "Archives Alphonse StYves",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Alphonse_StYves.jpg",
			status: false,
		},
		{
			id: "box1archive2",
			title: "Archives Armand Beaux",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Armand_Beaux.jpg",
			status: false,
		},
		{
			id: "box1archive3",
			title: "Archives Axelle Charpentier",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Axelle_Charpentier.jpg",
			status: false,
		},
		{
			id: "box1archive4",
			title: "Archives Camille Michaux",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Camille_Michaux.jpg",
			status: false,
		},
		{
			id: "box1archive5",
			title: "Archives Charles Garraud",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Charles_Garraud.jpg",
			status: false,
		},
		{
			id: "box1archive6",
			title: "Archives Christian Patenaud",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Christian_Patenaude.jpg",
			status: false,
		},
		{
			id: "box1archive7",
			title: "Archives Christophe Brunelle",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Christophe_Brunelle.jpg",
			status: false,
		},
		{
			id: "box1archive8",
			title: "Archives Didier Rodin",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Didier_Rodin.jpg",
			status: false,
		},
		{
			id: "box1archive9",
			title: "Archives Elisabeth Monrency",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Elisabeth_Monrency.jpg",
			status: false,
		},
		{
			id: "box1archive10",
			title: "Archives Elodie Bouchard",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Elodie_Bouchard.jpg",
			status: false,
		},
		{
			id: "box1archive11",
			title: "Archives Emmanuel Deslauriers",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Emmanuel_Deslauriers.jpg",
			status: false,
		},
		{
			id: "box1archive12",
			title: "Archives Eugenie Courbis",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Eugenie_Courbis.jpg",
			status: false,
		},
		{
			id: "box1archive13",
			title: "Archives Frederic Masse",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Frederic_Masse.jpg",
			status: false,
		},
		{
			id: "box1archive14",
			title: "Archives Jacqueline Houdin",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Jacqueline_Houdin.jpg",
			status: false,
		},
		{
			id: "box1archive15",
			title: "Archives Johanna Lesbourg",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Johanna_Lesbourg.jpg",
			status: false,
		},
		{
			id: "box1archive16",
			title: "Archives Marianne Chauve",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Marianne_Chauve.jpg",
			status: false,
		},
		{
			id: "box1archive17",
			title: "Archives Marie Marquis",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Marie_Marquis.jpg",
			status: false,
		},
		{
			id: "box1archive18",
			title: "Archives Maxence Maret",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Maxence_Maret.jpg",
			status: false,
		},
		{
			id: "box1archive19",
			title: "Archives Nicolas Chaussee",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Nicolas_Chaussee.jpg",
			status: false,
		},
		{
			id: "box1archive20",
			title: "Archives Patrick O'Neil",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Patrick_Oneill.jpg",
			status: false,
		},
		{
			id: "box1archive21",
			title: "Archives Robert Dumont",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Robert_Dumont.jpg",
			status: false,
		},
		{
			id: "box1archive22",
			title: "Archives Violaine Celier",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Violaine_Celier.jpg",
			status: false,
		},
		{
			id: "box1archive23",
			title: "Archives Xavier Monrency",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Xavier_Monrency.jpg",
			status: false,
		},
		{
			id: "box1archive24",
			title: "Archives Yannick Becot",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/1_Archives_Yannick_Becot.jpg",
			status: false,
		},

		// ----- DOCUMENT ----- //

		{
			id: "box1document1",
			title: "Malle ouverte",
			category: "Document",
			detail: "",
			poster: "assets/document/101_Malle_ouverte_LD.jpg",
			src: "assets/document/101_Malle_ouverte_LD.jpg",
			status: false,
		},
		{
			id: "box1document2",
			title: "Carte lieu final",
			category: "Document",
			detail: "",
			poster: "assets/document/103_Carte_lieu_final.jpg",
			src: "assets/document/103_Carte_lieu_final.jpg",
			status: false,
		},
		{
			id: "box1document3",
			title: "Guide du profiler",
			category: "Document",
			detail: "",
			poster: "assets/document/104_Guide_du_profiler.jpg",
			src: "assets/document/104_Guide_du_profiler.pdf",
			status: false,
		},
		{
			id: "box1document4",
			title: "Rapport légiste Xavier Monrency",
			category: "Document",
			detail: "",
			poster: "assets/document/124_Rapport_leÌgiste_Xavier_Monrency.jpg",
			src: "assets/document/124_Rapport_leÌgiste_Xavier_Monrency.jpg",
			status: false,
		},
		{
			id: "box1document5",
			title: "Email tueur",
			category: "Document",
			detail: "",
			poster: "assets/document/125_Email_Tueur_OublieÌ.png",
			src: "assets/document/125_Email_Tueur_OublieÌ.png",
			status: false,
		},
		{
			id: "box1document6",
			title: "Message planque tueur",
			category: "Document",
			detail: "",
			poster: "assets/document/126_Message_dans_la_planque.jpg",
			src: "assets/document/126_Message_dans_la_planque.pdf",
			status: false,
		},
		{
			id: "box1document7",
			title: "Lettre pour Garraud",
			category: "Document",
			detail: "",
			poster: "assets/document/130_Lettre_pour_Garraud.jpg",
			src: "assets/document/130_Lettre_pour_Garraud.pdf",
			status: false,
		},

		// ---- INTERROGATOIRES ---- //
		{
			id: "box1audio1",
			title: "Derniers mots de Rebecca",
			category: "Audio",
			detail: "",
			poster: "assets/photos-personnages/rebecca_dumont.jpg",
			img1: "assets/photos-personnages/rebecca_dumont.jpg",
			img2: null,
			srcAudio: "sounds/102-derniers-mots-rebecca.wav",
			srcTranscript: "assets/transcripts/102_Derniers_mots_Rebecca_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio2",
			title: "Interrogatoire Adèle Leinu",
			category: "Audio",
			detail: "",
			poster: "",
			img1: "",
			img2: "",
			srcAudio: "sounds/106-interrogatoire-adele-lauren.wav",
			srcTranscript: "assets/transcripts/106_Interrogatoire_AdeÌ€le-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio3",
			title: "Interrogatoire Alphonse St-Yves",
			category: "Audio",
			detail: "",
			poster: "assets/photos-personnages/Alphonse Saint-Yves.jpg",
			img1: "assets/photos-personnages/Alphonse Saint-Yves.jpg",
			img2: "",
			srcAudio: "sounds/107-interrogatoire-alphonse-st-yves-lauren.wav",
			srcTranscript: "assets/transcripts/107_Interrogatoire_Alphonse_St_Yves-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio4",
			title: "Interrogatoire Armand Beaux",
			category: "Audio",
			detail: "",
			poster: "assets/photos-personnages/Armand-Beaux.jpg",
			img1: "assets/photos-personnages/Armand-Beaux.jpg",
			img2: "",
			srcAudio: "sounds/108-interrogatoire-armand-beaux-lauren.wav",
			srcTranscript: "assets/transcripts/108_Interrogatoire_Armand_Beaux-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio5",
			title: "Interrogatoire Axelle Charpentier",
			category: "Audio",
			detail: "",
			poster: "assets/photos-personnages/Axelle-Charpentier.jpg",
			img1: "assets/photos-personnages/Axelle-Charpentier.jpg",
			img2: "",
			srcAudio: "sounds/109-interrogatoire-axelle-charpentier-celine.wav",
			srcTranscript: "assets/transcripts/109_Interrogatoire_Axelle_Charpentier-Celine_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio6",
			title: "Interrogatoire Camille Michaux",
			category: "Audio",
			detail: "",
			poster: "assets/photos-personnages/Camille-Michaux.jpg",
			img1: "assets/photos-personnages/Camille-Michaux.jpg",
			img2: "",
			srcAudio: "sounds/110-interrogatoire-camille-michaux-lauren.wav",
			srcTranscript: "assets/transcripts/110_Interrogatoire_Camille_Michaux-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio7",
			title: "Interrogatoire Christian Patenaude",
			category: "Audio",
			detail: "",
			poster: "assets/photos-personnages/Elisabeth-Monrency.jpg",
			img1: "assets/photos-personnages/Elisabeth-Monrency.jpg",
			img2: "assets/photos-personnages/Christian-Patenaude.jpg",
			srcAudio: "sounds/111-interrogatoire-christian-patenaude-elisabeth-monrency.wav",
			srcTranscript: "assets/transcripts/111_Interrogatoire_Christian_Patenaude-Elisabeth_Monrency_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio8",
			title: "Interrogatoire Emmanuel Deslauriers",
			category: "Audio",
			detail: "",
			poster: "assets/photos-personnages/Emmanuel-Deslauriers.jpg",
			img1: "assets/photos-personnages/Emmanuel-Deslauriers.jpg",
			img2: "",
			srcAudio: "sounds/112-interrogatoire-emmanuel-deslauriers-lauren.wav",
			srcTranscript: "assets/transcripts/112_Interrogatoire_Emmanuel_Deslauriers-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio9",
			title: "Interrogatoire Eugénie Courbis",
			category: "Audio",
			detail: "",
			poster: "assets/photos-personnages/Eugenie-Courbis.jpg",
			img1: "assets/photos-personnages/Eugenie-Courbis.jpg",
			img2: "",
			srcAudio: "sounds/113-interrogatoire-eugenie-courbis-lauren.wav",
			srcTranscript: "assets/transcripts/113_Interrogatoire_EugeÌnie_Courbis-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio10",
			title: "Interrogatoire Maxence Maret",
			category: "Audio",
			detail: "",
			poster: "assets/photos-personnages/Maxence-Maret.jpg",
			img1: "assets/photos-personnages/Maxence-Maret.jpg",
			img2: "",
			srcAudio: "sounds/114-interrogatoire-maxence-maret-lauren.wav",
			srcTranscript: "assets/transcripts/114_Interrogatoire_Maxence_Maret-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio11",
			title: "Interrogatoire Robert Dumont",
			category: "Audio",
			detail: "",
			poster: "assets/photos-personnages/Robert Dumont.jpg",
			img1: "assets/photos-personnages/Robert Dumont.jpg",
			img2: "",
			srcAudio: "sounds/115-interrogatoire-robert-dumont-lauren.wav",
			srcTranscript: "assets/transcripts/115_Interrogatoire_Robert_Dumont-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio12",
			title: "Interrogatoire Patrick O'Neil",
			category: "Audio",
			detail: "",
			poster: "assets/photos-personnages/Patrick O'Neil.jpg",
			img1: "assets/photos-personnages/Patrick O'Neil.jpg",
			img2: "",
			srcAudio: "sounds/116-interrogatoire-patrick-o-neil-lauren.wav",
			srcTranscript: "assets/transcripts/116_Interrogatoire_Patrick_O'Neil-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio13",
			title: "Interrogatoire Violaine Celier",
			category: "Audio",
			detail: "",
			poster: "assets/photos-personnages/Violaine-Cellier.jpg",
			img1: "assets/photos-personnages/Violaine-Cellier.jpg",
			img2: "",
			srcAudio: "sounds/117-interrogatoire-violaine-celier-lauren.wav",
			srcTranscript: "assets/transcripts/117_Interrogatoire_Violaine_Celier-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box1audio14",
			title: "Interrogatoire Yannick Bécot",
			category: "Audio",
			detail: "",
			poster: "assets/photos-personnages/Yannick-Becot.jpg",
			img1: "assets/photos-personnages/Yannick-Becot.jpg",
			img2: "",
			srcAudio: "sounds/118-interrogatoire-yannick-becot-lauren.wav",
			srcTranscript: "assets/transcripts/118_Interrogatoire_Yannick_BeÌcot-Lauren_transcript.pdf",
			status: false,
		},

		// ---- VIDEOS ---- //

		{
			id: "box1video1",
			title: "Introduction Box 1",
			category: "Video",
			detail: "",
			poster: "thumbnails/db-s02-101-assemblagefinal-v3-miniature.png",
			src: "videos/db-s02-101-def.mp4",
			status: false,
		},
		{
			id: "box1video2",
			title: "Fouille terrain",
			category: "Video",
			detail: "",
			poster: "thumbnails/db-s02-102-def-miniature.png",
			src: "videos/db-s02-102-def.mp4",
			status: false,
		},
		{
			id: "box1video3",
			title: "VHS",
			category: "Video",
			detail: "",
			poster: "thumbnails/db-s02-103-def-miniature.png",
			src: "videos/db-s02-103-def-1.mp4",
			status: false,
		},
		{
			id: "box1video4",
			title: "Interrogatoire de Garraud",
			category: "Video",
			detail: "thumbnails/db-s02-104-def-miniature.png",
			poster: "videos/db-s02-104-vdef.mp4",
			src: "",
			status: false,
		},

		// ---- LIEU ---- //

		{
			id: "box1lieu1",
			title: "Lieu de fouille Chantier",
			category: "Lieu",
			detail: "",
			poster: "assets/miniature-lieu-de-fouille/103_Planque_1.jpg",
			src: "",
			status: false,
		},
		{
			id: "box1lieu2",
			title: "Lieu de fouille Terrain",
			category: "Lieu",
			detail: "",
			poster: "102_Lieu_crime_Terrain.jpg",
			src: "",
			status: false,
		},
		{
			id: "box1lieu3",
			title: "Lieu de fouille Planque",
			category: "Lieu",
			detail: "",
			poster: "103_Planque_1.jpg",
			src: "",
			status: false,
		},
	],

	// ---- BOX 2 ---- //

	box2: [
		// ----- ARCHIVES ----- //

		{
			id: "box2archive1",
			title: "Archives Aaron King",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Aaron_King.jpg",
			status: false,
		},
		{
			id: "box2archive2",
			title: "Archives Ainmir Oconradh",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Ainmire_Oconradh.jpg",
			status: false,
		},
		{
			id: "box2archive3",
			title: "Archives Annelijn Dikboom",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Annelijn_dikboom.jpg",
			status: false,
		},
		{
			id: "box2archive4",
			title: "Archives Annina Kurschner",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Annina_Kurschner.jpg",
			status: false,
		},
		{
			id: "box2archive5",
			title: "Archives Augustas Alsys",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Augustas_Alsys.jpg",
			status: false,
		},
		{
			id: "box2archive6",
			title: "Archives Bogdana Nikol",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Bogdana_Nikol.jpg",
			status: false,
		},
		{
			id: "box2archive7",
			title: "Archives Daisy Vandenbulcke",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Daisy_Vandenbulcke.jpg",
			status: false,
		},
		{
			id: "box2archive8",
			title: "Archives Dimosthenis Rigas",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Dimosthenis_Rigas.jpg",
			status: false,
		},
		{
			id: "box2archive9",
			title: "Archives Dominik Jele",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Dominik_Jele.jpg",
			status: false,
		},
		{
			id: "box2archive10",
			title: "Archives Edvard Kallio",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Edvard_Kallio.jpg",
			status: false,
		},
		{
			id: "box2archive11",
			title: "Archives Elias Varelas",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Elias_Varelas.jpg",
			status: false,
		},
		{
			id: "box2archive13",
			title: "Archives Elimena Furino",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Elimena_Furino.jpg",
			status: false,
		},
		{
			id: "box2archive14",
			title: "Archives Eliza Gaewska",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Eliza_Gaewska.jpg",
			status: false,
		},
		{
			id: "box2archive15",
			title: "Archives Era Jakobson",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Ere_Jakobson.jpg",
			status: false,
		},
		{
			id: "box2archive16",
			title: "Archives Francois Duchamp",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Francois_Duchamp.jpg",
			status: false,
		},
		{
			id: "box2archive17",
			title: "Archives Horasiu Prunea",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Horasiu_Prunea.jpg",
			status: false,
		},
		{
			id: "box2archive18",
			title: "Archives Imelda Tuzzolino",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Imelda_Tuzzolino.jpg",
			status: false,
		},
		{
			id: "box2archive19",
			title: "Archives Ivar Mortensen",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Ivar_Mortensen.jpg",
			status: false,
		},
		{
			id: "box2archive20",
			title: "Archives James Chambers",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_James_Chambers.jpg",
			status: false,
		},
		{
			id: "box2archive21",
			title: "Archives Janina Muster",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Janina_Muster.jpg",
			status: false,
		},
		{
			id: "box2archive22",
			title: "Archives Jorn Frenzel",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Jorn_Frenzel.jpg",
			status: false,
		},
		{
			id: "box2archive23",
			title: "Archives Karina Galicka",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Karina_Galicka.jpg",
			status: false,
		},
		{
			id: "box2archive24",
			title: "Archives Konstantin Wallner",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Konstantin_Wallner.jpg",
			status: false,
		},
		{
			id: "box2archive25",
			title: "Archives Laura Tavernier",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Laura_Tavernier.jpg",
			status: false,
		},
		{
			id: "box2archive26",
			title: "Archives Lina Syren",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Lina_Syren.jpg",
			status: false,
		},
		{
			id: "box2archive27",
			title: "Archives Linda Reynolds",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Linda_Reynolds.jpg",
			status: false,
		},
		{
			id: "box2archive28",
			title: "Archives Marian Bilek",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Marian_Bilek.jpg",
			status: false,
		},
		{
			id: "box2archive29",
			title: "Archives Marike Vonbraun",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Marike_Vonbraun.jpg",
			status: false,
		},
		{
			id: "box2archive30",
			title: "Archives Martin Richard",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Martin_Richard.jpg",
			status: false,
		},
		{
			id: "box2archive31",
			title: "Archives Mason Reynolds",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Mason_Reynolds.jpg",
			status: false,
		},
		{
			id: "box2archive32",
			title: "Archives Petar Cojocaru",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Petar_Cojocaru.jpg",
			status: false,
		},
		{
			id: "box2archive33",
			title: "Archives Riano Della Valle",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Riano_Della_Valle.jpg",
			status: false,
		},
		{
			id: "box2archive33",
			title: "Archives Samuel Perry",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Samuel_Perry.jpg",
			status: false,
		},
		{
			id: "box2archive34",
			title: "Archives Taneli Tuominen",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Taneli_Tuominen.jpg",
			status: false,
		},
		{
			id: "box2archive35",
			title: "Archives Timo Sladie",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/2_Archives_Timo_Sladie.jpg",
			status: false,
		},

		// ---- DOCUMENT ---- //

		{
			id: "box2document1",
			title: "Planque du tueur",
			category: "Document",
			detail: "",
			poster: "assets/document/202_Planque_tueur.png",
			src: "assets/document/202_Planque_tueur.png",
			status: false,
		},
		{
			id: "box2document2",
			title: "Livre ''Lilith et la guérison des maux''",
			category: "Document",
			detail: "",
			poster: "",
			src: "assets/document/213_Livre_Lilith_incomplet.pdf",
			status: false,
		},
		{
			id: "box2document3",
			title: "Livre ''Je commence l'Origami''",
			category: "Document",
			detail: "",
			poster: "",
			src: "assets/document/214_Livre_Origami.pdf",
			status: false,
		},
		{
			id: "box2document4",
			title: "Papier avalé par Garraud",
			category: "Document",
			detail: "",
			poster: "assets/document/215_Papier_avaleÌ.jpg",
			src: "assets/document/215_Papier_avaleÌ.jpg",
			status: false,
		},
		{
			id: "box2document5",
			title: "Lettre de Stella",
			category: "Document",
			detail: "",
			poster: "assets/document/216_Lettre_de_Stella.jpg",
			src: "assets/document/216_Lettre_de_Stella.pdf",
			status: false,
		},
		{
			id: "box2document6",
			title: "Notes sur Lauren Fraser",
			category: "Document",
			detail: "",
			poster: "assets/document/217_Message_sur_lieu_de_fouille.png",
			src: "assets/document/217_Message_sur_lieu_de_fouille.png",
			status: false,
		},
		{
			id: "box2document7",
			title: "Poster Rabid Star Slayer",
			category: "Document",
			detail: "",
			poster: "assets/document/218_Poster_Rabid_Star_Slayer.png",
			src: "assets/document/218_Poster_Rabid_Star_Slayer.png",
			status: false,
		},
		{
			id: "box2document8",
			title: "Email Lauren #1",
			category: "Document",
			detail: "",
			poster: "assets/document/219_Message_Lauren_#1.jpg",
			src: "assets/document/219_Message_Lauren_#1.jpg",
			status: false,
		},
		{
			id: "box2document9",
			title: "Email Lauren #2",
			category: "Document",
			detail: "",
			poster: "assets/document/220_Message_Lauren_#2.jpg",
			src: "assets/document/220_Message_Lauren_#2.jpg",
			status: false,
		},
		{
			id: "box2document10",
			title: "Photo Jacqueline Houdin",
			category: "Document",
			detail: "",
			poster: "assets/document/221_Photo_Jacqueline_Houdin.jpg",
			src: "assets/document/221_Photo_Jacqueline_Houdin.pdf",
			status: false,
		},

		// ---- INTERROGATOIRES ---- //

		{
			id: "box2audio1",
			title: "Interrogatoire Martin Richard",
			category: "Audio",
			detail: "",
			poster: "assets/photos-personnages/Martin Richard.jpg",
			img1: "assets/photos-personnages/Martin Richard.jpg",
			img2: "",
			srcAudio: "sounds/205-interrogatoire-martin-richard-lauren.wav",
			srcTranscript: "assets/transcripts/205_Interrogatoire_Martin_Richard-Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box2audio2",
			title: "Interrogatoire Linda Reynolds",
			category: "Audio",
			detail: "",
			poster: "assets/photos-personnages/Linda Reynolds.jpg",
			img1: "assets/photos-personnages/Linda Reynolds.jpg",
			img2: "assets/photos-personnages/Jaden-Gill.jpg",
			srcAudio: "sounds/206-interrogatoire-linda-reynolds-agent-db.wav",
			srcTranscript: "assets/transcripts/206_Interrogatoire_Linda_Reynolds-Jaden_Gill_transcript.pdf",
			status: false,
		},
		{
			id: "box2audio3",
			title: "Echanges Samuel Perry & Raphaëlle Sanchez",
			category: "Audio",
			detail: "",
			poster: "",
			img1: "",
			img2: "",
			srcAudio: "sounds/207-echanges-samuel-perry-raphaelle.wav",
			srcTranscript: "assets/transcripts/207_Echanges_Samuel_Perry-RaphaeÌˆlle_transcript.pdf",
			status: false,
		},
		{
			id: "box2audio4",
			title: "Echange Alphonse St-Yves",
			category: "Audio",
			detail: "",
			poster: "assets/photos-personnages/Alphonse Saint-Yves.jpg",
			img1: "assets/photos-personnages/Alphonse Saint-Yves.jpg",
			img2: "",
			srcAudio: "sounds/208-interrogatoire-alphonse-saint-yves-lauren.wav",
			srcTranscript: "assets/transcripts/208_Interrogatoire_Alphonse_Saint-Yves-Lauren_transcript.pdf",
			status: false,
		},

		// ---- VIDEOS ---- //

		{
			id: "box2video1",
			title: "Introduction Box 2",
			category: "Video",
			detail: "",
			poster: "thumbnails/db-s02-201-def-miniature.png",
			src: "videos/db-s02-201-vdef.mp4",
			status: false,
		},
		{
			id: "box2video2",
			title: "Webcam Mason",
			category: "Video",
			detail: "",
			poster: "thumbnails/db-s02-202-webcam-mason-v1-miniature.png",
			src: "videos/db-s02-202-webcam-mason-v1.mp4",
			status: false,
		},
		{
			id: "box2video3",
			title: "Breaking News",
			category: "Video",
			detail: "",
			poster: "thumbnails/db-s02-203-def-miniature.png",
			src: "videos/db-s02-203-vdef.mp4",
			status: false,
		},
		{
			id: "box2video4",
			title: "Frigo",
			category: "Video",
			detail: "",
			poster: "thumbnails/db-s02-207-def-miniature.png",
			src: "videos/db-s02-207-def.mp4",
			status: false,
		},
		{
			id: "box2video5",
			title: "Fin Box 2",
			category: "Video",
			detail: "",
			poster: "thumbnails/db-s02-210-def-miniature.png",
			src: "videos/db-s02-209-vdef.mp4",
			status: false,
		},

		// ---- LIEU ---- //

		{
			id: "box2lieu1",
			title: "Lieu de fouille Chez Mason",
			category: "Lieu",
			detail: "",
			poster: "assets/miniature-lieu-de-fouille/201_Chez_Mason.jpg",
			src: "",
			status: false,
		},
		{
			id: "box2lieu2",
			title: "Lieu de fouille cellule Garraud",
			category: "Lieu",
			detail: "",
			poster: "assets/miniature-lieu-de-fouille/202 _Prison_cellule_Garraud.jpg",
			src: "",
			status: false,
		},
		{
			id: "box2lieu3",
			title: "Lieu de fouille appartement Stella",
			category: "Lieu",
			detail: "",
			poster: "assets/miniature-lieu-de-fouille/203_Planque_2 _appartement.jpg",
			src: "",
			status: false,
		},
	],

	// ---- BOX 3 ---- //

	box3: [
		// ----- ARCHIVES ----- //

		{
			id: "box3archive1",
			title: "Archives Agnes Vouchiar",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/3_Archives_Agnes_Vouchiar.jpg",
			status: false,
		},
		{
			id: "box3archive2",
			title: "Archives Giuseppe Rossi",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/3_Archives_Giuseppe_Rossi.jpg",
			status: false,
		},
		{
			id: "box3archive3",
			title: "Archives Leonie Brugmann",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/3_Archives_Leonie_Brugmann.jpg",
			status: false,
		},
		{
			id: "box3archive4",
			title: "Archives Maria Gruber",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/3_Archives_Maria_Gruber.jpg",
			status: false,
		},
		{
			id: "box3archive5",
			title: "Archives Yann Lacroix",
			category: "Archive",
			detail: "",
			poster: "",
			src: "assets/archive/3_Archives_Yann_Lacroix.jpg",
			status: false,
		},

		// ---- DOCUMENT ---- //

		{
			id: "box3document1",
			title: "Post-it bureau Lauren",
			category: "Document",
			detail: "",
			poster: "assets/document/304_Post_it.jpg",
			src: "assets/document/304_Post_it.jpg",
			status: false,
		},
		{
			id: "box3document2",
			title: "Photo squelette forêt",
			category: "Document",
			detail: "",
			poster: "assets/document/312_Photo_squelette_deÌterreÌ.jpg",
			src: "assets/document/312_Photo_squelette_deÌterreÌ.jpg",
			status: false,
		},
		{
			id: "box3document3",
			title: "Photo hôpital",
			category: "Document",
			detail: "",
			poster: "assets/document/313_Photo_Estelle_hopital.jpg",
			src: "assets/document/313_Photo_Estelle_hopital.jpg",
			status: false,
		},
		{
			id: "box3document4",
			title: "Photo Loic Valluy",
			category: "Document",
			detail: "",
			poster: "assets/document/314_Photo_Loic_Valluy.jpg",
			src: "assets/document/314_Photo_Loic_Valluy.jpg",
			status: false,
		},
		{
			id: "box3document5",
			title: "Dossier médical Céline",
			category: "Document",
			detail: "",
			poster: "assets/document/316_Dossier_CeÌline.jpg",
			src: "assets/document/316_Dossier_CeÌline.pdf",
			status: false,
		},
		{
			id: "box3document6",
			title: "Dossier médical Estelle",
			category: "Document",
			detail: "",
			poster: "",
			src: "assets/document/317_Dossier_Estelle.pdf",
			status: false,
		},
		{
			id: "box3document7",
			title: "Dossier médical Estelle",
			category: "Document",
			detail: "",
			poster: "",
			src: "assets/document/319_Livre_Lilith_complet.pdf",
			status: false,
		},
		{
			id: "box3document8",
			title: "Reçu de la poste",
			category: "Document",
			detail: "",
			poster: "assets/document/320_Recu_poste.jpg",
			src: "assets/document/320_Recu_poste.pdf",
			status: false,
		},
		{
			id: "box3document9",
			title: "Carnet d'Estelle",
			category: "Document",
			detail: "",
			poster: "assets/document/321_Carnet_Estelle.jpg",
			src: "assets/document/321_Carnet_Estelle.pdf",
			status: false,
		},
		{
			id: "box3document10",
			title: "Tableau des victimes",
			category: "Document",
			detail: "",
			poster: "assets/document/322_Tableau_CeÌline.jpg",
			src: "assets/document/322_Tableau_CeÌline.jpg",
			status: false,
		},
		{
			id: "box3document11",
			title: "Arbre généalogique",
			category: "Document",
			detail: "",
			poster: "assets/document/325_Arbre_geÌneÌalogique.jpg",
			src: "assets/document/325_Arbre_geÌneÌalogique.pdf",
			status: false,
		},
		{
			id: "box3document12",
			title: "Liste des donneurs potentiels",
			category: "Document",
			detail: "",
			poster: "assets/document/327_Liste_des_donneurs.jpg",
			src: "assets/document/327_Liste_des_donneurs.pdf",
			status: false,
		},

		// ---- INTERROGATOIRES ---- //

		{
			id: "box3audio1",
			title: "Débrief Lauren",
			category: "Audio",
			detail: "",
			poster: "",
			img1: "",
			img2: "",
			srcAudio: "sounds/303-debrief-lauren.wav",
			srcTranscript: "assets/transcripts/303_Debrief_Lauren_transcript.pdf",
			status: false,
		},
		{
			id: "box3audio2",
			title: "Interrogatoire Leonie Brugmann",
			category: "Audio",
			detail: "",
			poster: "assets/photos-personnages/Leonie-Brugmann.jpg",
			img1: "assets/photos-personnages/Leonie-Brugmann.jpg",
			img2: "assets/photos-personnages/Rebekka-Auer.jpg",
			srcAudio: "sounds/311-interrogatoire-leonie-brugmann-rebekka-auer.wav",
			srcTranscript: "assets/transcripts/311_Interrogatoire_Leonie_Brugmann-Rebekka_Auer_transcript.pdf",
			status: false,
		},
		{
			id: "box3audio3",
			title: "Interrogatoire Yann Lacroix",
			category: "Audio",
			detail: "",
			poster: "assets/photos-personnages/Yann Lacroix.jpg",
			img1: "assets/photos-personnages/Yann Lacroix.jpg",
			img2: "",
			srcAudio: "sounds/312-interrogatoire-yann-lacroix-raphaelle.wav",
			srcTranscript: "assets/transcripts/312_Interrogatoire_Yann_Lacroix-RaphaeÌˆlle_transcript.pdf",
			status: false,
		},
		{
			id: "box3audio4",
			title: "Interrogatoire François Duchamp",
			category: "Audio",
			detail: "",
			poster: "assets/photos-personnages/FrancÌ§ois-Duchamp.jpg",
			img1: "assets/photos-personnages/FrancÌ§ois-Duchamp.jpg",
			img2: "",
			srcAudio: "sounds/313-interrogatoire-francÌ§ois-duchamp-raphaelle.wav",
			srcTranscript: "assets/transcripts/313_Interrogatoire_FrancÌ§ois_Duchamp-RaphaeÌˆlle_transcript.pdf",
			status: false,
		},

		// ---- VIDEOS ---- //

		{
			id: "box3video1",
			title: "Introduction Box 3",
			category: "Video",
			detail: "",
			poster: "thumbnails/db-s02-301-def-miniature.png",
			src: "videos/db-s02-301-def.mp4",
			status: false,
		},
		{
			id: "box3video2",
			title: "Retrouver Lauren",
			category: "Video",
			detail: "",
			poster: "thumbnails/db-s02-302-def-miniature.png",
			src: "videos/db-s02-302-def.mp4",
			status: false,
		},
		{
			id: "box3video2",
			title: "Fin Box 3",
			category: "Video",
			detail: "",
			poster: "thumbnails/db-s02-309-assemblagefin-v1-1-1-miniature.png",
			src: "videos/db-s02-309-def.mp4",
			status: false,
		},

		// ---- LIEU ---- //

		{
			id: "box3lieu1",
			title: "Lieu de fouille Forêt",
			category: "Lieu",
			detail: "",
			poster: "assets/miniature-lieu-de-fouille/301_ForeÌ‚t.jpg",
			src: "",
			status: false,
		},
		{
			id: "box3lieu2",
			title: "Lieu de fouille chez Céline",
			category: "Lieu",
			detail: "",
			poster: "assets/miniature-lieu-de-fouille/302_chez_Celine.jpg",
			src: "",
			status: false,
		},
		{
			id: "box3lieu3",
			title: "Lieu de fouille Cave",
			category: "Lieu",
			detail: "",
			poster: "assets/miniature-lieu-de-fouille/303_Planque_3_cave.jpg",
			src: "",
			status: false,
		},
	],
};
